# Generated by Django 3.2.9 on 2023-03-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230311_1340'),
    ]

    operations = [
     #   migrations.AlterField(
       #     model_name='blog',
      #      name='is_active',
       #     field=models.BooleanField(default=True),
       # ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
      #  migrations.AlterField(
       #     model_name='category',
      #      name='name',
       #     field=models.CharField(max_length=160),
        #),
    ]
